version: "3"
services:
  bitcoin-core:
    container_name: bitcoin-core
    image: ruimarinho/bitcoin-core:0.19.1-alpine
    command:
      -printtoconsole
      -testnet=1
      -txindex=1
      -server=1
    environment:
      - BITCOIN_DATA=/data
    volumes:
      - ${DATA_VOL}:/data
  ion-core:
    container_name: ion-core
    image: identityfoundation/ion:latest
    command: "core"
    ports: 
      - "80:3000"
    links:
      - "ion-bitcoin"
      - "ion-ipfs"
      - "mongo"
  ion-bitcoin:
    container_name: ion-bitcoin
    image: identityfoundation/ion:latest
    command: "bitcoin"
    ports: 
      - "80:3002"
    links:
      - "bitcoin-core"
      - "mongo"
  ion-ipfs:
    container_name: ion-ipfs
    image: identityfoundation/ion:latest
    command: "ipfs"
    ports: 
      - "80:3003"
    depends_on:
      - "ion-bitcoin"
  mongo:
    container_name: mongo
    image: mongo:3.6.18-xenial
    volumes:
      - ${DB_VOL}:/data/db